CREATE TABLE `belle_atendimentos` (
  `id` int AUTO_INCREMENT NOT NULL,
  `unidadeId` int NOT NULL,
  `atendimentoBelleId` bigint NOT NULL,
  `clienteId` int,
  `clienteNome` varchar(200) NOT NULL,
  `telefone` varchar(30),
  `dataAtendimento` varchar(10) NOT NULL,
  `horario` varchar(8),
  `servicoCodigo` int,
  `servicoNome` varchar(250),
  `duracaoMinutos` int,
  `profissionalNome` varchar(200),
  `temPreferencia` boolean NOT NULL DEFAULT false,
  `planoBelleId` bigint,
  `areaAplicacao` text,
  `tipo` varchar(80),
  `status` varchar(80) NOT NULL,
  `importadoEm` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `belle_atendimentos_id` PRIMARY KEY(`id`),
  CONSTRAINT `belle_atendimentos_unidade_externo_idx` UNIQUE(`unidadeId`,`atendimentoBelleId`),
  KEY `belle_atendimentos_unidade_cliente_data_idx` (`unidadeId`,`clienteId`,`dataAtendimento`),
  KEY `belle_atendimentos_unidade_data_idx` (`unidadeId`,`dataAtendimento`)
);
